export const GET_EVENTS = "GET_EVENTS";

export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const GET_SPECIFIC_EVENT = "GET_SPECIFIC_EVENT";

export const GET_SPECIFIC_EVENT_FAILURE = "GET_SPECIFIC_EVENT_FAILURE";

export const GET_SPECIFIC_EVENT_SUCCESS = "GET_SPECIFIC_EVENT_SUCCESS";

export const SUBSCRIBE_EVENT = "SUBSCRIBE_EVENT";

export const SUBSCRIBE_EVENT_FAILURE = "SUBSCRIBE_EVENT_FAILURE";

export const SUBSCRIBE_EVENT_SUCCESS = "SUBSCRIBE_EVENT_SUCCESS";

export const UNSUBSCRIBE_EVENT = "UNSUBSCRIBE_EVENT";

export const UNSUBSCRIBE_EVENT_FAILURE = "UNSUBSCRIBE_EVENT_FAILURE";

export const UNSUBSCRIBE_EVENT_SUCCESS = "UNSUBSCRIBE_EVENT_SUCCESS";

export const CREATE_EVENT = "CREATE_EVENT";

export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";

export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";

export const DELETE_EVENT = "DELETE_EVENT";

export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
