export const GET_EVENTS = "GET_EVENTS";

export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const SUBSCRIBE_EVENT = "SUBSCRIBE_EVENT";

export const SUBSCRIBE_EVENT_FAILURE = "SUBSCRIBE_EVENT_FAILURE";

export const SUBSCRIBE_EVENT_SUCCESS = "SUBSCRIBE_EVENT_SUCCESS";

export const UNSUBSCRIBE_EVENT = "UNSUBSCRIBE_EVENT";

export const UNSUBSCRIBE_EVENT_FAILURE = "UNSUBSCRIBE_EVENT_FAILURE";

export const UNSUBSCRIBE_EVENT_SUCCESS = "UNSUBSCRIBE_EVENT_SUCCESS";
