export const GET_ACCOUNT = "GET_ACCOUNT";

export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE";

export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";

export const EDIT_ACCOUNT = "EDIT_ACCOUNT";

export const EDIT_ACCOUNT_FAILURE = "EDIT_ACCOUNT_FAILURE";

export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const DELETE_ACCOUNT_FAILURE = "DELETE_ACCOUNT_FAILURE";

export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";

export const GET_ALL_USERS = "GET_ALL_USERS";

export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const DELETE_ACCOUNT_ADMIN = "DELETE_ACCOUNT_ADMIN";

export const DELETE_ACCOUNT_ADMIN_FAILURE = "DELETE_ACCOUNT_ADMIN_FAILURE";

export const DELETE_ACCOUNT_ADMIN_SUCCESS = "DELETE_ACCOUNT_ADMIN_SUCCESS";

export const EDIT_ROLE = "EDIT_ROLE";

export const EDIT_ROLE_FAILURE = "EDIT_ROLE_FAILURE";

export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
